import type { AppDefinition } from '@goose/types';

export const APPS: AppDefinition[] = [
  {
    id: 'files',
    name: 'Files',
    description: 'Browse your home directory',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#2563EB',
    kind: 'ready',
    defaultSize: { w: 720, h: 470 },
  },
  {
    id: 'editor',
    name: 'Text Editor',
    description: 'Write notes and code',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#0D9488',
    kind: 'ready',
    defaultSize: { w: 680, h: 460 },
  },
  {
    id: 'search',
    name: 'Search',
    description: 'Find files, apps and the web',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#4F46E5',
    kind: 'ready',
    defaultSize: { w: 640, h: 500 },
  },
  {
    id: 'browser',
    name: 'Browser',
    description: 'Prototype web browser',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#2563EB',
    kind: 'ready',
    defaultSize: { w: 880, h: 560 },
  },
  {
    id: 'app-center',
    name: 'App Center',
    description: 'Discover and launch applications',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#C2410C',
    kind: 'ready',
    defaultSize: { w: 760, h: 540 },
  },
  {
    id: 'settings',
    name: 'Settings',
    description: 'Customise GOOSE OS',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#64748B',
    kind: 'ready',
    defaultSize: { w: 640, h: 500 },
  },
  {
    id: 'system-monitor',
    name: 'System Monitor',
    description: 'Watch CPU, memory and battery',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#0EA5E9',
    kind: 'ready',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'music',
    name: 'Music',
    description: 'Listen to your library',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#DB2777',
    kind: 'ready',
    defaultSize: { w: 420, h: 600 },
  },
  {
    id: 'ai-center',
    name: 'AI Assistant',
    description: 'Gemini-powered assistance (preview)',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#9333EA',
    kind: 'preview',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'trash',
    name: 'Trash',
    description: 'Items you deleted',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#6B7280',
    kind: 'ready',
    defaultSize: { w: 560, h: 420 },
  },
  {
    id: 'terminal',
    name: 'Terminal',
    description: 'Shell with GOOSE assist',
    pinned: true,
    defaultWorkspace: 0,
    tint: '#16A34A',
    kind: 'ready',
    defaultSize: { w: 680, h: 410 },
  },
  {
    id: 'developer-center',
    name: 'Developer Center',
    description: 'Projects, tools and templates (preview)',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#2563EB',
    kind: 'preview',
    defaultSize: { w: 760, h: 540 },
  },
  {
    id: 'google-drive',
    name: 'Google Drive',
    description: 'Files and cloud storage',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 720, h: 500 },
  },
  {
    id: 'google-docs',
    name: 'Google Docs',
    description: 'Write and edit documents',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Spreadsheets and data',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'google-slides',
    name: 'Google Slides',
    description: 'Presentations',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 760, h: 520 },
  },
  {
    id: 'google-photos',
    name: 'Google Photos',
    description: 'Photo library',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'google-meet',
    name: 'Google Meet',
    description: 'Video meetings',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 880, h: 560 },
  },
  {
    id: 'google-chat',
    name: 'Google Chat',
    description: 'Team messaging',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 720, h: 520 },
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Email',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 760, h: 560 },
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Schedules and events',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 880, h: 560 },
  },
  {
    id: 'google-tasks',
    name: 'Google Tasks',
    description: 'To-dos and checklists',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 560, h: 520 },
  },
  {
    id: 'google-keep',
    name: 'Google Keep',
    description: 'Notes and lists',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#F9AB00',
    kind: 'ready',
    defaultSize: { w: 620, h: 460 },
  },
  {
    id: 'google-voice',
    name: 'Google Voice',
    description: 'Voicemail and calls',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 520, h: 640 },
  },
  {
    id: 'google-forms',
    name: 'Google Forms',
    description: 'Surveys and quizzes',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 660, h: 560 },
  },
  {
    id: 'google-sites',
    name: 'Google Sites',
    description: 'Quick websites',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 760, h: 540 },
  },
  {
    id: 'google-maps',
    name: 'Google Maps',
    description: 'Maps and directions',
    pinned: false,
    defaultWorkspace: 0,
    tint: '#1A73E8',
    kind: 'ready',
    defaultSize: { w: 760, h: 560 },
  },
];

const FALLBACK_APP: AppDefinition = {
  id: 'unknown',
  name: 'App',
  description: '',
  pinned: false,
  defaultWorkspace: 0,
  tint: '#C2410C',
};

export function appById(id: string): AppDefinition {
  return APPS.find((app) => app.id === id) ?? FALLBACK_APP;
}